# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Dxx
subtitle: Dxx
description: good good study day day up
keyword: dxx, java，学习，瞎搞，游玩，折腾
bio: A simple Developer

author: Dxx
language: en
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://shakalaka.xyz/hexo-theme-dxx
root: /hexo-theme-dxx/
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:


disqus_shortname: dxx
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

#gentie_productKey: f813692f917647bda87b2bbadb1284ae

# Pagination
## Set per_page to 0 to disable pagination
#per_page: 5
pagination_dir: page

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 1
#category: 2
#tag: 2

#主页每页显示文章数
index_generator:
 per_page: 10
#archive归档文章显示条数
archive_generator:
 per_page: 20
 yearly: true
 monthly: true
#tag
#tag_generator:
# per_page: 5
#category
#category_generator: 
# per_page: 5

#feed
feed:
  type: atom
  path: /atom.xml
  limit: 20

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

#baidusitemap:
#  path: baidusitemap.xml
sitemap:
  path: sitemap.xml

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: hexo-theme-curry
#theme: adoubi
theme: dxx

googleVerification: MGkmt8k-JS4yE1jlkL1vKcsX6VXUfsqwYCdW8TaSpPU
googleAnalytics: UA-115898584-1

#live2d:
#  enable: true
#  scriptFrom: local
#  model:
#    use: live2d-widget-model-hijiki
#  display:
#    position: left
#    width: 100
#    height: 200
#  mobile:
#    show: false

# Deployment
## Docs: https://hexo.io/docs/deployment.html
#deploy:
#  type: git
#  repo: https://github.com/fuzhouxxdong/fuzhouxxdong.github.io.git
#  branch: master
deploy:
  type: git
  repo:
      github: https://github.com/fuzhouxxdong/fuzhouxxdong.github.io.git,master
#      github: https://github.com/fuzhouxxdong/fuzhouxxdong.github.io.git,master
#      coding: https://git.coding.net/dfz/dfz.coding.me.git,master
